### ISSUE TITLE
Add class when element becomes visible

### ISSUE THREAD

**Issue by Ghost180195** [scrollreveal/scrollreveal#394]
Hello!
It would be cool if you implemented such a function.
That is, only the class name is added to the element without any animations.

**Comment by jlmakes** [comment]
This has come up before (#143), but I’m not sure how I feel about officially adding this to the API since so much of ScrollReveal's code is dedicated to creating animations.

That said, even if it’s not baked-in, this is now possible with [v4](https://unpkg.com/scrollreveal@beta) because:

- CSS Transform styles are no longer generated unless needed.
- `options.opacity` now accepts `null` to skip generating opacity styles.

That means a configuration like this would essentially do nothing, but give you access to callbacks:

```js
var options = {

    delay:    0,
    distance: 0,
    duration: 0,
    scale:    1,
    opacity:  null,

    rotate: {
        x: 0,
        y: 0,
        z: 0
     },

    afterReset: function (el) {},
    afterReveal: function (el) {},
    beforeReset: function (el) {},
    beforeReveal: function (el) {}
}
```

You can see how this can be [monkey patched](https://github.com/jlmakes/scrollreveal/issues/337#issuecomment-309657013) to create a new `watch()` method that would allow you to do this:

```js
ScrollReveal().watch('.items', function (el) {
    el.classList.add('active')
}, function (el) {
    el.classList.remove('active')
})
```
