### ISSUE TITLE
Performance: Consider passive eventlisteners

### ISSUE THREAD

**Issue by sfunke** [scrollreveal/scrollreveal#416]
Hey, firstly thanks for the fantastic library.

My suggestion for further improving scrolling performance is adding the scrolling event listeners passively.

With the option `{ passive: true }` added to event listeners, they cannot be canceled and are delivered right down the chain, without the browser waiting for the code in the listener to execute. This can improve scrolling performance dramatically.

See here:

https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners
https://developers.google.com/web/updates/2016/06/passive-event-listeners
https://alligator.io/js/speed-up-scroll-events/

What do you think about it to the library, and would you accept pull requests?

**Comment by jlmakes** [comment]
I think it's a great idea. For some reason I thought all scroll event listeners were passive by default in browsers that support them—but that doesn't appear to be the case!

I'm open to pull requests, I ask that you:

- use lowercase commit messages with imperative mood
- make sure to work off of the development branch

```bash
# Fork the repository on GitHub, then...
git clone -b development "https://github.com/YOUR-USERNAME/scrollreveal.git"
cd scrollreveal
git checkout -b "your-new-branch-name"
```

In this particular case, I think implementing [feature detection](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection) and updating the [initialize](https://github.com/jlmakes/scrollreveal/blob/development/src/instance/functions/initialize.js#L24-L25) method accordingly would be awesome! Otherwise, I don't mind implementing this for the next beta release.

**Comment by jlmakes** [comment]
> Note: The basic `scroll` event cannot be canceled, so it does not need to be set passive. ([Source](https://developers.google.com/web/updates/2016/06/passive-event-listeners))
