### ISSUE TITLE
When using sync() all previously loaded items disappear 

### ISSUE THREAD

**Issue by modestasu** [scrollreveal/scrollreveal#468]
Hey! 

Firs of all great work, I love this plugin and it was such an easy setup so for.

However, I've noticed a strange behaviour when using .sync() items that were previously loaded and were visible disappear and only the ones in viewport show. Here's a quick screencast of what I mean - https://screencast-o-matic.com/watch/cF6bc1YUBW

And here's a JSbin test - https://jsbin.com/miguyoxiqo/edit?html,output

Is this a normal behaviour? Am I missing something obvious here? 

My goal is to update and reload only specific sections on a website homepage while keeping the rest intact. I thought calling .sync() would work this way.

**Comment by jlmakes** [comment]
Thanks for sharing this @modestasu, it's definitely a bug!

**Comment by ZNS** [comment]
Also ran into this. Is it possible to downgrade to a version that works for now?

**Comment by jlmakes** [comment]
I'm not sure, but a new release is coming soon @ZNS

**Comment by ZNS** [comment]
Alright, sounds good. {reset:true} works as a workaround for now but it's not the behaviour I want

**Comment by alexgil1994** [comment]
Hello,
I have some trouble using the library with the same behavior as mentioned above. I will explain farther, I actually use the library through another one that helps preparing it to use it in VueJs applications , the library is called v-scroll-reveal. It's basically only a wrapper of the original i think.<br/>
So I have used it in 2 websites so far, the first one ( done a couple months ago ) doesn't seem to have a problem with visible sections disappearing.<br>
The one I am working on now ( personal website ) does show the problem but not in every page. ( website is alexandrosmarkovic.com )
Basically on the landing page if one scrolls down things work but if you go up and and open the menu and close it then they start disappearing. Especially if you are through phone and you open the menu with touch left-to-right while on top of dissapeared sections and close the menu again then the dissappeared sections re-appear. It 's a weird behavior. I don't know if it has to do anything with Vuetify's navigation drawer though probably it doesn't since i see it's called as a bug here. On the opposite if you go to other pages like the 'programming' you will see that there is no problem which is weird because i use a similar layout there - the navigation drawer is basically the same.<br>
If needed I will also mention the other website which I did before which has no problem ( the v-scroll-reveal package on that one is the 1.0.8 if that helps to see which scroll-reveal release it uses while on the new page i use the 1.0.11 ).<br>
I hope I did the right thing posting this here instead of v-scroll-reveal package, if not inform me and I will delete the comment.

**Comment by alexgil1994** [comment]
Just found what caused the problem for me, I am also using Vuetify's `scroll.to` method for smooth scrolling to specific element in the page, this probably conflicts with vue-scroll-reveal ( etc. scroll-reveal inside it ). <br>I don't there a solution to keep both so I ll probably disable one.<br> I apologize for the confusion. ( if needed inform to delete the comments to avoid any more confusion ).

**Comment by alexgil1994** [comment]
Ok, so I kept testing it and i found out it wasn't the method i am using from Vuetify to smoothly scroll towards an element. The problem was that I had the animation effect on that `Welcome button` you can see in the front page. By removing the animation effect on it the elements stop disappearing when I open the navigation drawer. It is a bit weird I think. I found out after removing the Vuetify method while still having trouble, then I tried randomly to comment the button element and that's how i figured it out. <br>I don't know if this is a random behavior, hopefully saying it will help into finding the bug.
<br>I am showing the before and after of the code :

Before
```
        <div style="top: 73%; position: absolute;"  v-scroll-reveal="{ delay: 800, duration: 1300, scale: 0.8, origin: 'bottom', distance: '5px'}">
          <v-btn @click="$vuetify.goTo(target, options)" depressed light color="rgba(255,255,255,0.1)">
            <h4 class="teal--text text--lighten-1">{{ welcomeText }}</h4>
            <v-icon right color="teal text-lighten-1">keyboard_arrow_down</v-icon>
          </v-btn>
        </div>

```

After
```
        <div style="top: 73%; position: absolute;">
          <v-btn @click="$vuetify.goTo(target, options)" depressed light color="rgba(255,255,255,0.1)">
            <h4 class="teal--text text--lighten-1">{{ welcomeText }}</h4>
            <v-icon right color="teal text-lighten-1">keyboard_arrow_down</v-icon>
          </v-btn>
        </div>
```

**Comment by jlmakes** [comment]
Your situation seems directly related to your use of 3rd party scripts @alexgil1994.
If you're still having problems, please open a new issue (either here, or with the 3rd party).

**Comment by jlmakes** [comment]
### Please patch to `4.0.5`

@modestasu @ZNS @alexgil1994
