### ISSUE TITLE
Problem of resolution?

### ISSUE THREAD

**Issue by lionelbovy** [scrollreveal/scrollreveal#477]
Hello,

Here's a video illustrating my issue: https://www.youtube.com/watch?v=j_OW-lQeYP0
If you want to test the website, I host it here: https://www.beta.bovy.fr/YaliAIR/index.html

### Environment

* Operating System: macOS 10.14.1 (18B75)
* Browser Version: Chrome Version 70.0.3538.102 (Official build) (64 bits)
* ScrollReveal Version: 4.0.5

**Comment by jlmakes** [comment]
Hey @lionelbovy 

I appreciate your patience, and the detailed issue report. 

On desktop, you use the windows scrollbar...
On mobile, you use the `.site-content` scrollbar.

So to start with you had this...

```js
// before
sr.reveal('.card', { delay: 300, interval: 200, scale: 0.85 });
```

For your reveals to work on mobile, you need to specify `.site-content` as your `option.container`. (Otherwise it will listen to the wrong `scroll` events.) Since `options.desktop` and `options.mobile` are `true` by default, we can just _turn off_ the unrelated platform for each configuration, e.g:

```js
ScrollReveal({ delay: 300, interval: 200, scale: 0.85 });

sr.reveal('.card', mobile: false });
sr.reveal('.card', desktop: false, container: '.site-content' });
```

> This is one way to configure separate desktop/mobile reveals, but keep in mind, it will not work when resizing the window because `options.desktop` and `options.mobile` do not use window width—they use the device user agent. _So to test things, actually load it on a mobile device._
