### ISSUE TITLE
SR not working sometimes

### ISSUE THREAD

**Issue by MariuzM** [scrollreveal/scrollreveal#490]
So i have this code, and sometime on Chrome it works sometimes all images are just displayed. On firefox i'm having more issues more times if not all the time that it does not work. Am i missing something? 

```js
ScrollReveal().reveal('.grid_item img', {
  // scale: 0.7,
  opacity: 0,
  delay: 200,
  duration: 1000
});
```

**Comment by jlmakes** [comment]
You have to be careful when revealing images. Images typically change dimensions while the page is loading, from a small empty square to the final image. If you use ScrollReveal without waiting for your images to finish loading, ScrollReveal will operate on the small empty squares.

**Comment by jlmakes** [comment]
You have to be careful when revealing images.

Images typically change dimensions while the page is loading (from a "small empty square" to the final image). If you use ScrollReveal without waiting for your images to finish loading, ScrollReveal will operate on these "small empty squares".

This has negative consequences, because the dimensions and visibility properties will be incorrect. I recommend looking into techniques for invoking your scripts _after_ images have finished loading.

**Comment by MariuzM** [comment]
I see i will try something and will report back tomorrow

**Comment by MariuzM** [comment]
I think it worked for now, i will close this case tomorrow just want to do some more testing but this is what i used:

```
window.addEventListener('load', () => {
	// More stuff happening before this
  ScrollReveal().reveal('.grid_item img', {
    opacity: 0,
    delay: 200,
    duration: 1000
  });
});
```
